/**
 * Standard API error codes — see docs/BACKEND_ARCHITECTURE.md §15
 */
export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  QUOTE_EXPIRED: 'QUOTE_EXPIRED',
  QC_REQUIRED: 'QC_REQUIRED',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  OPTIMISTIC_LOCK: 'OPTIMISTIC_LOCK',
  IDEMPOTENCY_REPLAY: 'IDEMPOTENCY_REPLAY',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
